# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='pricehistory',
            table='price_history',
        ),
    ]
