# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0002_auto_20200513_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
