# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0004_auto_20200513_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='date',
        ),
    ]
