# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0005_remove_pricehistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
