# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0010_auto_20200513_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
