# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0012_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
