# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0015_auto_20200513_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='updated_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
