# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0016_auto_20200513_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='created',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at'),
        ),
    ]
