# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0017_auto_20200513_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
