# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0018_auto_20200513_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
